version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - pervasive
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/
      - /etc/letsencrypt/:/etc/letsencrypt/
  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: post
      POSTGRES_USER: postgres
    networks:
      - pervasive
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    container_name: frontend
    image: pervasivesmartlock.azurecr.io/pervasive-frontend:0.1.0
    environment:
      - REACT_APP_BASE_URL=http://pervasive.julandoomar.xyz
    networks:
      - pervasive
  backend:
    container_name: backend
    image: pervasivesmartlock.azurecr.io/pervasive-backend:0.1.0
    env_file:
      - ./backend.env
    networks:
      - pervasive
    depends_on:
      - postgresql

networks:
  pervasive:
    external: true

volumes:
  postgres_data:
    external: true